### ISSUE TITLE
Update for Gutenberg 10.7

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/thisis#32]
Gutenberg 10.7 is coming soon. 

I pulled the source code yesterday and rebuilt it. 

I needed to update node.js to a new version.
On my Windows machine I found that the easiest way to do this was to downloading v14.7.0 LTS from https://nodejs.org/en/
LTS stands for Long Term Support.

Having activated the newly built version in `s.b/wp55/thisis` I noticed a few changes on the front end. 
These need to be investigated, and the changes accounted for. 
I hope this means I'll have to make changes to my code rather than reporting issues.

#### Front page
- Site Logo disappeared again
- Latest posts section is not shown in 3 columns
-

**Comment by bobbingwide** [comment]
> Site Logo disappeared again.

- The site logo did not appear on the front end.
- When I added a new post to test the Site Logo block it was broken. Never ending spinner.

![image](https://user-images.githubusercontent.com/2474435/119126109-87858780-ba2a-11eb-8eba-39bd1094f11d.png)

- I then deactivated all plugins
- Which trigger an unexpected Fatal error due to some tracing I'd added to class-wp-query
- The system then reported that the theme was broken
- Now my site's completely broken with a Fatal error
-  it seems to have switched to no theme at all.
- and I can't activate an new theme

**Comment by bobbingwide** [comment]
```
[21-May-2021 11:03:46 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in C:\apache\htdocs\wp55\wp-includes\theme.php:1063
Stack trace:
#0 C:\apache\htdocs\wp55\wp-includes\nav-menu.php(1170): set_theme_mod('nav_menu_locati...', Array)
#1 C:\apache\htdocs\wp55\wp-includes\class-wp-hook.php(294): _wp_menus_changed('Twenty Twenty-O...')
#2 C:\apache\htdocs\wp55\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 C:\apache\htdocs\wp55\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#4 C:\apache\htdocs\wp55\wp-includes\theme.php(3302): do_action('after_switch_th...', 'Twenty Twenty-O...', Object(WP_Theme))
#5 C:\apache\htdocs\wp55\wp-includes\class-wp-hook.php(292): check_theme_switched('')
#6 C:\apache\htdocs\wp55\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#7 C:\apache\htdocs\wp55\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#8 C:\apache\htdocs\wp55\wp-settings.php(560): do_action('init')
#9 C:\apache\htdocs\wp55\wp-config.php(111): require_once('C:\\apache\\htdoc...')
#10 C:\apache\htdocs\wp55\wp-load.php(37): require_once('C:\\apache\\htdoc...')
#11 C:\apache\htdocs\wp55\wp-admin\admin.php(34): require_once('C:\\apache\\htdoc...')
#12 C:\apache\htdocs\wp55\wp-admin\themes.php(10): require_once('C:\\apache\\htdoc...')
#13 {main}
  thrown in C:\apache\htdocs\wp55\wp-includes\theme.php on line 1063
```

**Comment by bobbingwide** [comment]
While the main site is broken I tried on `s.b/wp55/universal` with TT1 blocks.
The response to the request initiated when adding the Site Logo block is
![image](https://user-images.githubusercontent.com/2474435/119131619-99b6f400-ba31-11eb-85f6-286626feafd5.png)

**Comment by bobbingwide** [comment]
With 10.6.0 it's different.
![image](https://user-images.githubusercontent.com/2474435/119132109-32e60a80-ba32-11eb-863c-f070a43819e2.png)

**Comment by aristath** [comment]
Found the problem with the site-logo block, I'll be submitting a PR in a few minutes.

**Comment by aristath** [comment]
PR in https://github.com/WordPress/gutenberg/pull/32092

**Comment by bobbingwide** [comment]
> Now my site's completely broken with a Fatal error

I resolved this problem by deleting the empty `theme_mods_thisis` option from the wp_options table.

**Comment by bobbingwide** [comment]
> Latest posts section is not shown in 3 columns

It would appear that the `layout` attribute has been renamed to `displayLayout` to take into account the `layout` option that's been added to negate the need to wrap it in a Group block. See https://github.com/wordpress/gutenberg/pull/31833

The new version of the `latest-posts.html` template part now has both attributes. Both appear to have the values
`{"type":"flex","columns":3}`.


```
...
<!-- wp:query {"queryId":7,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"displayLayout":{"type":"flex","columns":3},"layout":{"type":"flex","columns":3}} -->
<div class="wp-block-query"><!-- wp:query-loop -->
...
```
    
    <main class="wp-block-group" style="padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px">

        

        </main>
    
    </div>

**Comment by bobbingwide** [comment]
> Both appear to have the same values.... {"type":"flex","columns":3}.

This was because I hadn't touched the Inherit default layout toggle in the Layout pane. 
Toggling it off and on altered the attribute values.

```
<!-- wp:query {"queryId":7,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"asc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"displayLayout":{"type":"flex","columns":4},"layout":{"inherit":true}} -->
<div class="wp-block-query">
```

**Comment by bobbingwide** [comment]
I imagine I'll have to check all uses of the query block.
Note also that I'd previously got away with not having a `div class="wp-block-query">` start and end tag.

**Comment by bobbingwide** [comment]
> PHP Fatal error:  Uncaught TypeError: 
Cannot access offset of type string on string in C:\apache\htdocs\wp55\wp-includes\theme.php:1063

This problem also occurred on `blocks.wp.a2z` as I was trying to get Fizzie to work with Gutenberg 10.7.1.

**Comment by bobbingwide** [comment]
The Page List block in the sidebar is only showing the top level pages, and the ordering is still not good enough.
